application: ifcdb-hrd
version: coming-soon
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /
  static_files: index.html
  upload: index.html
