application: ifcdb-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

#error_handlers:
#...

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
- url: /datastore_admin
  script: google.appengine.ext.datastore_admin.main.APP
#- url: /stats.*
#  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: webapp2
  version: "2.5.1"
#- name: lxml
#  version: "2.3"

builtins:
- appstats: on
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
#- ^(lib/webapp2)
#- ^(lib/jinja2)
#- ^(lib/ndb)

admin_console:
 pages:
 - name: Appstats
   url: /stats
